apiVersion: v1
kind: AgentSpec
name: lead.scorer
version: 1.0.0
owner: AIAIAI Consulting
description: "Calificación automática de leads basada en perfil, comportamiento y fit con el producto"
responsibility: "Analizar y calificar leads automáticamente para priorizar esfuerzos de ventas"

# Input Schema
inputs:
  lead_profile:
    type: object
    required: true
    properties:
      name:
        type: string
        description: "Nombre completo del lead"
      email:
        type: string
        format: email
        description: "Email de contacto"
      company:
        type: string
        description: "Empresa del lead"
      industry:
        type: string
        enum: ["technology", "retail", "manufacturing", "services", "healthcare", "finance", "education", "other"]
        description: "Industria de la empresa"
      company_size:
        type: string
        enum: ["startup", "small", "medium", "enterprise"]
        description: "Tamaño de la empresa"
      role:
        type: string
        description: "Cargo del lead en la empresa"
      budget_range:
        type: string
        enum: ["<10k", "10k-50k", "50k-100k", "100k-500k", ">500k"]
        description: "Rango de presupuesto estimado"
      timeline:
        type: string
        enum: ["immediate", "1-3months", "3-6months", "6-12months", ">12months"]
        description: "Timeline de implementación"
      source:
        type: string
        description: "Fuente del lead (website, referral, etc.)"
      behavior_data:
        type: object
        properties:
          website_visits:
            type: integer
            description: "Número de visitas al website"
          page_views:
            type: integer
            description: "Páginas vistas"
          time_on_site:
            type: integer
            description: "Tiempo en el sitio (segundos)"
          downloads:
            type: integer
            description: "Documentos descargados"
          email_opens:
            type: integer
            description: "Emails abiertos"
          email_clicks:
            type: integer
            description: "Clicks en emails"

# Output Schema
outputs:
  lead_score:
    type: object
    properties:
      overall_score:
        type: integer
        minimum: 0
        maximum: 100
        description: "Puntuación general del lead (0-100)"
      category:
        type: string
        enum: ["hot", "warm", "cold"]
        description: "Categoría del lead"
      confidence:
        type: number
        minimum: 0
        maximum: 1
        description: "Nivel de confianza en la calificación"
      factors:
        type: array
        items:
          type: object
          properties:
            factor:
              type: string
              description: "Factor evaluado"
            score:
              type: integer
              minimum: 0
              maximum: 100
              description: "Puntuación del factor"
            weight:
              type: number
              description: "Peso del factor en la puntuación final"
            reasoning:
              type: string
              description: "Explicación del factor"
      recommendations:
        type: array
        items:
          type: string
        description: "Recomendaciones de acción"
      next_steps:
        type: array
        items:
          type: string
        description: "Próximos pasos sugeridos"

# Policies
policies:
  mode: ["auto", "review", "approve"]
  sla_seconds: 30
  retry_attempts: 3
  timeout_seconds: 60

# Tools and Integrations
tools:
  - crm.update
  - email.send
  - analytics.track
  - calendar.schedule

# Observability
observability:
  metrics:
    - latency_ms
    - tokens_used
    - retry_count
    - accuracy_score
  logs:
    level: "info"
    format: "structured"
  alerts:
    - high_latency
    - low_accuracy
    - high_error_rate

# Business Rules
business_rules:
  scoring_weights:
    company_fit: 0.3
    budget_alignment: 0.25
    timeline_urgency: 0.2
    behavior_engagement: 0.15
    source_quality: 0.1
  
  thresholds:
    hot_lead: 80
    warm_lead: 60
    cold_lead: 40
  
  industry_multipliers:
    technology: 1.2
    finance: 1.1
    healthcare: 1.0
    retail: 0.9
    manufacturing: 0.8

# Examples
examples:
  input_example:
    lead_profile:
      name: "María González"
      email: "maria@techcorp.cl"
      company: "TechCorp Chile"
      industry: "technology"
      company_size: "medium"
      role: "CTO"
      budget_range: "50k-100k"
      timeline: "1-3months"
      source: "website"
      behavior_data:
        website_visits: 15
        page_views: 45
        time_on_site: 1200
        downloads: 3
        email_opens: 8
        email_clicks: 5
  
  output_example:
    lead_score:
      overall_score: 85
      category: "hot"
      confidence: 0.92
      factors:
        - factor: "Company Fit"
          score: 90
          weight: 0.3
          reasoning: "Empresa tecnológica con CTO como decisor"
        - factor: "Budget Alignment"
          score: 80
          weight: 0.25
          reasoning: "Presupuesto dentro del rango objetivo"
        - factor: "Timeline Urgency"
          score: 85
          weight: 0.2
          reasoning: "Timeline de 1-3 meses indica urgencia"
        - factor: "Behavior Engagement"
          score: 88
          weight: 0.15
          reasoning: "Alto engagement con múltiples visitas y downloads"
        - factor: "Source Quality"
          score: 75
          weight: 0.1
          reasoning: "Lead orgánico del website"
      recommendations:
        - "Contactar inmediatamente por teléfono"
        - "Enviar propuesta personalizada"
        - "Programar demo técnico"
      next_steps:
        - "Llamada de calificación en 24 horas"
        - "Envío de case study relevante"
        - "Invitation a webinar técnico"
